# Site settings
title: Design System Resources
description: A collaborative collection of resources for design systems, front-End style guides, and component-based design and development.
baseurl: ""

example-title: "Design System Examples"
example-description: "A collection of design systems and style guides out in the wild."

resource-title: "Resources"
resource-description: "Articles, talks, slides, and more all about design systems and style guides"

tool-title: "Tools"
tool-description: "Things to help you make design systems happen."

# Build settings
markdown: kramdown

collections:
    ds-article:
        output: true
    ds-book:
        output: true
    ds-example:
        output: true
    ds-podcast:
        output: true
    ds-resource:
        output: true
    ds-talk:
        output: true
    ds-tool:
        output: true
    podcast:
        output: true
    patterns:
        output: true
