# Site settings
title: Design System Resources
description: A collaborative collection of resources for design systems, front-End style guides, and component-based design and development.
baseurl: ""

article-title: "Articles"
article-description: "Things people have written about style guides."

book-title: "Books"
book-description: "Books written about style guides."

example-title: "Examples"
example-description: "Real life pattern libraries, code standards documents and content style guides."

podcast-title: "Podcasts"
podcast-description: "Episodes from various podcasts where style guides are discussed."

talk-title: "Talks"
talk-description: "Conference presentations about style guides."

tool-title: "Tools"
tool-description: "Things to help you make your own style guide."

# Build settings
markdown: kramdown

collections:
    resourcearticle:
        output: true
    resourcebook:
        output: true
    resourceexample:
        output: true
    resourcepodcast:
        output: true
    resourcetalk:
        output: true
    resourcetool:
        output: true
    podcast:
        output: true
    patterns:
        output: true
